# Stores settings for tei-iiif converter
%YAML 1.2
---
temp_dir: "./temp/"
base_path: "https://raw.githubusercontent.com/JoshuaAPhillips/digital-anon/main/transcriptions/" # Base path for requests. This can be a URI (e.g.: https://foo.bar/baz/xml-files/) or local (e.g.: /home/user/xml-files/).
namespace: {'tei': 'http://www.tei-c.org/ns/1.0'} #Defaults to TEI namespace








# ../digital-anon/transcriptions/
#file_name: "sys.argv[-1]" # Need to work out logic for this... It's hardcoded as sys.argv[-1] for now